[features]
seeds = true
skip-lint = false

[programs.localnet]
seagull = "5m6icMgJpaZoWywACLyRtTrdZ52FUoR6x6iuciKky9J2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/chase/.config/solana/id.json"

[scripts]
test = "yarn workspace integration test"
