[features]
seeds = true
skip-lint = false

[programs.localnet]
seagull = "DmcruH9NFwSAxZL4u1UdQd3S5TQdS8SQGFjFbng5KBEC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/chase/.config/solana/id.json"

[scripts]
test = "yarn workspace integration test"
